#!/usr/bin/env bash

## author: KleiberXD

set -e

export KAD_DIR="$(cd "$(dirname "${BASH_SOURCE-$0}")" && pwd)"

source ${KAD_DIR}/commands/deploy.sh
source ${KAD_DIR}/commands/docker.sh
source ${KAD_DIR}/commands/install.sh
source ${KAD_DIR}/commands/registry.sh
source ${KAD_DIR}/commands/uninstall.sh

# export all config variables
export $(cat "$KAD_DIR/conf/config" | xargs)

kad_version() {
    local kad_version=$(cat ${KAD_DIR}/conf/VERSION)
    echo "${CLI_NAME} version ${kad_version}"
}

kad_help() {
    cat <<EOF

kad tool helps to install and manage Kubernetes clusters.

 Find more information at: https://github.com/Kleiber/kad

Usage:  kad COMMAND [OPTIONS]

Commands:
  deploy      Deploy using helm values
  docker      Manage Docker images
  install     Install tools
  registry    Manage Docker registry
  uninstall   Uninstall tools

Options:
      --debug     Enable debug mode
  -h, --help      Show more information about command
  -v, --version   Show the kad version information

Run 'kad COMMAND --help' for more information about a given command.
EOF
}

kad_cmd() {
    local command=${1}

    case ${command} in
        deploy)
            shift
            deploy_cmd ${@}
            ;;
        docker)
            shift
            docker_cmd ${@}
            ;;
        install)
            shift
            install_cmd ${@}
            ;;
        registry)
            shift
            registry_cmd ${@}
            ;;
        uninstall)
            shift
            uninstall_cmd ${@}
            ;;
        --version | -v)
            kad_version
            ;;
        --help | -h | *)
            kad_help
            ;;
    esac
}

kad_cmd ${@}

