apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kad
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /hello
        backend:
          service:
            name: service-kad
            port:
              number: 8080