apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-kad
spec:
  selector:
    matchLabels:
      app: KadApp # has to match .spec.template.metadata.labels
  serviceName: "kad"
  replicas: 1
  template:
    metadata:
      labels:
        app: KadApp # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: container-kad
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{.Values.image.tag}}
          envFrom:
          - configMapRef:
              name: configmap-kad
          ports:
          - name: kad-port
            containerPort: 8080
